using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MESv2.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddDowntimeTracking : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "DowntimeThresholdMinutes",
                table: "WorkCenterProductionLines",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<bool>(
                name: "DowntimeTrackingEnabled",
                table: "WorkCenterProductionLines",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AlterColumn<Guid>(
                name: "ProductionRecordId",
                table: "Annotations",
                type: "uniqueidentifier",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier");

            migrationBuilder.AddColumn<Guid>(
                name: "DowntimeEventId",
                table: "Annotations",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "SerialNumberId",
                table: "Annotations",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "SystemTypeInfo",
                table: "Annotations",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "DowntimeReasonCategories",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    PlantId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    SortOrder = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DowntimeReasonCategories", x => x.Id);
                    table.ForeignKey(
                        name: "FK_DowntimeReasonCategories_Plants_PlantId",
                        column: x => x.PlantId,
                        principalTable: "Plants",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "DowntimeReasons",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    DowntimeReasonCategoryId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    SortOrder = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DowntimeReasons", x => x.Id);
                    table.ForeignKey(
                        name: "FK_DowntimeReasons_DowntimeReasonCategories_DowntimeReasonCategoryId",
                        column: x => x.DowntimeReasonCategoryId,
                        principalTable: "DowntimeReasonCategories",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "DowntimeEvents",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    WorkCenterProductionLineId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    OperatorUserId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    DowntimeReasonId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    StartedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    EndedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DurationMinutes = table.Column<decimal>(type: "decimal(10,2)", precision: 10, scale: 2, nullable: false),
                    IsAutoGenerated = table.Column<bool>(type: "bit", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DowntimeEvents", x => x.Id);
                    table.ForeignKey(
                        name: "FK_DowntimeEvents_DowntimeReasons_DowntimeReasonId",
                        column: x => x.DowntimeReasonId,
                        principalTable: "DowntimeReasons",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_DowntimeEvents_Users_OperatorUserId",
                        column: x => x.OperatorUserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_DowntimeEvents_WorkCenterProductionLines_WorkCenterProductionLineId",
                        column: x => x.WorkCenterProductionLineId,
                        principalTable: "WorkCenterProductionLines",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "WorkCenterProductionLineDowntimeReasons",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    WorkCenterProductionLineId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    DowntimeReasonId = table.Column<Guid>(type: "uniqueidentifier", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_WorkCenterProductionLineDowntimeReasons", x => x.Id);
                    table.ForeignKey(
                        name: "FK_WorkCenterProductionLineDowntimeReasons_DowntimeReasons_DowntimeReasonId",
                        column: x => x.DowntimeReasonId,
                        principalTable: "DowntimeReasons",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_WorkCenterProductionLineDowntimeReasons_WorkCenterProductionLines_WorkCenterProductionLineId",
                        column: x => x.WorkCenterProductionLineId,
                        principalTable: "WorkCenterProductionLines",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Annotations_DowntimeEventId",
                table: "Annotations",
                column: "DowntimeEventId");

            migrationBuilder.CreateIndex(
                name: "IX_Annotations_SerialNumberId",
                table: "Annotations",
                column: "SerialNumberId");

            migrationBuilder.CreateIndex(
                name: "IX_DowntimeEvents_DowntimeReasonId",
                table: "DowntimeEvents",
                column: "DowntimeReasonId");

            migrationBuilder.CreateIndex(
                name: "IX_DowntimeEvents_OperatorUserId",
                table: "DowntimeEvents",
                column: "OperatorUserId");

            migrationBuilder.CreateIndex(
                name: "IX_DowntimeEvents_WorkCenterProductionLineId_StartedAt",
                table: "DowntimeEvents",
                columns: new[] { "WorkCenterProductionLineId", "StartedAt" });

            migrationBuilder.CreateIndex(
                name: "IX_DowntimeReasonCategories_PlantId",
                table: "DowntimeReasonCategories",
                column: "PlantId");

            migrationBuilder.CreateIndex(
                name: "IX_DowntimeReasons_DowntimeReasonCategoryId",
                table: "DowntimeReasons",
                column: "DowntimeReasonCategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_WorkCenterProductionLineDowntimeReasons_DowntimeReasonId",
                table: "WorkCenterProductionLineDowntimeReasons",
                column: "DowntimeReasonId");

            migrationBuilder.CreateIndex(
                name: "IX_WorkCenterProductionLineDowntimeReasons_WorkCenterProductionLineId_DowntimeReasonId",
                table: "WorkCenterProductionLineDowntimeReasons",
                columns: new[] { "WorkCenterProductionLineId", "DowntimeReasonId" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_Annotations_DowntimeEvents_DowntimeEventId",
                table: "Annotations",
                column: "DowntimeEventId",
                principalTable: "DowntimeEvents",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Annotations_SerialNumbers_SerialNumberId",
                table: "Annotations",
                column: "SerialNumberId",
                principalTable: "SerialNumbers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Annotations_DowntimeEvents_DowntimeEventId",
                table: "Annotations");

            migrationBuilder.DropForeignKey(
                name: "FK_Annotations_SerialNumbers_SerialNumberId",
                table: "Annotations");

            migrationBuilder.DropTable(
                name: "DowntimeEvents");

            migrationBuilder.DropTable(
                name: "WorkCenterProductionLineDowntimeReasons");

            migrationBuilder.DropTable(
                name: "DowntimeReasons");

            migrationBuilder.DropTable(
                name: "DowntimeReasonCategories");

            migrationBuilder.DropIndex(
                name: "IX_Annotations_DowntimeEventId",
                table: "Annotations");

            migrationBuilder.DropIndex(
                name: "IX_Annotations_SerialNumberId",
                table: "Annotations");

            migrationBuilder.DropColumn(
                name: "DowntimeThresholdMinutes",
                table: "WorkCenterProductionLines");

            migrationBuilder.DropColumn(
                name: "DowntimeTrackingEnabled",
                table: "WorkCenterProductionLines");

            migrationBuilder.DropColumn(
                name: "DowntimeEventId",
                table: "Annotations");

            migrationBuilder.DropColumn(
                name: "SerialNumberId",
                table: "Annotations");

            migrationBuilder.DropColumn(
                name: "SystemTypeInfo",
                table: "Annotations");

            migrationBuilder.AlterColumn<Guid>(
                name: "ProductionRecordId",
                table: "Annotations",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uniqueidentifier",
                oldNullable: true);
        }
    }
}
