// <auto-generated />
using System;
using MESv2.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MESv2.Api.Migrations
{
    [DbContext(typeof(MesDbContext))]
    partial class MesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MESv2.Api.Models.ActiveSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastHeartbeatDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("SiteCode");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("ActiveSessions");
                });

            modelBuilder.Entity("MESv2.Api.Models.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnnotationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Flag")
                        .HasColumnType("bit");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolvedNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationTypeId");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("ProductionRecordId");

                    b.HasIndex("ResolvedByUserId");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("MESv2.Api.Models.AnnotationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OperatorCanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresResolution")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AnnotationTypes");
                });

            modelBuilder.Entity("MESv2.Api.Models.Assembly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlphaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TankSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("Assemblies");
                });

            modelBuilder.Entity("MESv2.Api.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LimbleIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MESv2.Api.Models.BarcodeCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardValue");

                    b.ToTable("BarcodeCards");
                });

            modelBuilder.Entity("MESv2.Api.Models.ChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChangeByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FromValueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecordTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ToValueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangeByUserId");

                    b.ToTable("ChangeLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.Characteristic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("SpecHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SpecLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SpecTarget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("MESv2.Api.Models.CharacteristicWorkCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacteristicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("CharacteristicWorkCenters");
                });

            modelBuilder.Entity("MESv2.Api.Models.ControlPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacteristicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGateCheck")
                        .HasColumnType("bit");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("ControlPlans");
                });

            modelBuilder.Entity("MESv2.Api.Models.DefectCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("DefectCodes");
                });

            modelBuilder.Entity("MESv2.Api.Models.DefectLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CharacteristicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultLocationDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.ToTable("DefectLocations");
                });

            modelBuilder.Entity("MESv2.Api.Models.DefectLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CharacteristicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DefectCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HydroRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InspectionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRepaired")
                        .HasColumnType("bit");

                    b.Property<string>("LocationDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RepairedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("DefectCodeId");

                    b.HasIndex("HydroRecordId");

                    b.HasIndex("InspectionRecordId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductionRecordId");

                    b.HasIndex("RepairedByUserId");

                    b.ToTable("DefectLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.DefectWorkCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefectCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EarliestDetectionWorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DefectCodeId");

                    b.HasIndex("EarliestDetectionWorkCenterId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("DefectWorkCenters");
                });

            modelBuilder.Entity("MESv2.Api.Models.HydroRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyAlphaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameplateSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyAlphaCode");

                    b.HasIndex("AssetId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("HydroRecords");
                });

            modelBuilder.Entity("MESv2.Api.Models.InspectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ControlPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ResultNumeric")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResultText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ControlPlanId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("InspectionRecords");
                });

            modelBuilder.Entity("MESv2.Api.Models.MaterialQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoilNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoilSlabNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("QueueType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShellSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("VendorHeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VendorMillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VendorProcessorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkCenterId", "Status");

                    b.ToTable("MaterialQueueItems");
                });

            modelBuilder.Entity("MESv2.Api.Models.NameplateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SerialNumber");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("NameplateRecords");
                });

            modelBuilder.Entity("MESv2.Api.Models.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("CurrentPlantGearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurrentPlantGearId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("MESv2.Api.Models.PlantGear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("PlantGears");
                });

            modelBuilder.Entity("MESv2.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameplateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SageItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TankSize")
                        .HasColumnType("int");

                    b.Property<string>("TankType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MESv2.Api.Models.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("MESv2.Api.Models.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("MESv2.Api.Models.ProductionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InspectionResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlantGearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductInId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductOutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SerialNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PlantGearId");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("WorkCenterId");

                    b.HasIndex("SerialNumberId", "WorkCenterId", "Timestamp");

                    b.ToTable("ProductionRecords");
                });

            modelBuilder.Entity("MESv2.Api.Models.RoundSeamSetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("Rs1WelderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Rs2WelderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Rs3WelderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Rs4WelderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TankSize")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkCenterId", "CreatedAt");

                    b.ToTable("RoundSeamSetups");
                });

            modelBuilder.Entity("MESv2.Api.Models.SerialNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoilNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HeadsVendorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HeatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("bit");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MillVendorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProcessorVendorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplaceBySNId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Rs1Changed")
                        .HasColumnType("bit");

                    b.Property<bool>("Rs2Changed")
                        .HasColumnType("bit");

                    b.Property<bool>("Rs3Changed")
                        .HasColumnType("bit");

                    b.Property<bool>("Rs4Changed")
                        .HasColumnType("bit");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HeadsVendorId");

                    b.HasIndex("MillVendorId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("ProcessorVendorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReplaceBySNId");

                    b.HasIndex("Serial");

                    b.HasIndex("SiteCode");

                    b.ToTable("SerialNumbers");
                });

            modelBuilder.Entity("MESv2.Api.Models.SiteSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BuildDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ColorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MasterScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantityComplete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TankSize")
                        .HasColumnType("int");

                    b.Property<string>("TankType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteCode");

                    b.ToTable("SiteSchedules");
                });

            modelBuilder.Entity("MESv2.Api.Models.SpotXrayIncrement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncrementNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectTank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InspectTankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<string>("LaneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ManufacturingLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam1FinalResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam1InitialResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam1ShotDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam1ShotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam2FinalResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam2InitialResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam2ShotDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam2ShotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam3FinalResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam3InitialResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam3ShotDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam3ShotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam4FinalResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam4InitialResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam4ShotDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seam4ShotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TankSize")
                        .HasColumnType("int");

                    b.Property<string>("Welder1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welder2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welder3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Welder4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ManufacturingLogId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("SpotXrayIncrements");
                });

            modelBuilder.Entity("MESv2.Api.Models.TraceabilityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromAlphaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FromSerialNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TankLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToAlphaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ToSerialNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("TraceabilityLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DefaultSiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCertifiedWelder")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequirePinForLogin")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RoleTier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultSiteId");

                    b.HasIndex("EmployeeNumber");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MESv2.Api.Models.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VendorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VendorType", "SiteCode");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("MESv2.Api.Models.WelderLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CharacteristicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.HasIndex("ProductionRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("WelderLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.WorkCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataEntryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MaterialQueueForWCId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWelders")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkCenterTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MaterialQueueForWCId");

                    b.HasIndex("WorkCenterTypeId");

                    b.ToTable("WorkCenters");
                });

            modelBuilder.Entity("MESv2.Api.Models.WorkCenterProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWelders")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("WorkCenterId", "ProductionLineId")
                        .IsUnique();

                    b.ToTable("WorkCenterProductionLines");
                });

            modelBuilder.Entity("MESv2.Api.Models.WorkCenterType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkCenterTypes");
                });

            modelBuilder.Entity("MESv2.Api.Models.WorkCenterWelder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkCenterId", "UserId")
                        .IsUnique();

                    b.ToTable("WorkCenterWelders");
                });

            modelBuilder.Entity("MESv2.Api.Models.XrayQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("XrayQueueItems");
                });

            modelBuilder.Entity("MESv2.Api.Models.ActiveSession", b =>
                {
                    b.HasOne("MESv2.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ProductionLine");

                    b.Navigation("User");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.Annotation", b =>
                {
                    b.HasOne("MESv2.Api.Models.AnnotationType", "AnnotationType")
                        .WithMany("Annotations")
                        .HasForeignKey("AnnotationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.User", "InitiatedByUser")
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.ProductionRecord", "ProductionRecord")
                        .WithMany("Annotations")
                        .HasForeignKey("ProductionRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnnotationType");

                    b.Navigation("InitiatedByUser");

                    b.Navigation("ProductionRecord");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("MESv2.Api.Models.Assembly", b =>
                {
                    b.HasOne("MESv2.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany("Assemblies")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Operator");

                    b.Navigation("ProductionLine");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.Asset", b =>
                {
                    b.HasOne("MESv2.Api.Models.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany("Assets")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionLine");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.ChangeLog", b =>
                {
                    b.HasOne("MESv2.Api.Models.User", "ChangeByUser")
                        .WithMany()
                        .HasForeignKey("ChangeByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangeByUser");
                });

            modelBuilder.Entity("MESv2.Api.Models.Characteristic", b =>
                {
                    b.HasOne("MESv2.Api.Models.ProductType", "ProductType")
                        .WithMany("Characteristics")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("MESv2.Api.Models.CharacteristicWorkCenter", b =>
                {
                    b.HasOne("MESv2.Api.Models.Characteristic", "Characteristic")
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany("CharacteristicWorkCenters")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Characteristic");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.ControlPlan", b =>
                {
                    b.HasOne("MESv2.Api.Models.Characteristic", "Characteristic")
                        .WithMany()
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany("ControlPlans")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Characteristic");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.DefectLocation", b =>
                {
                    b.HasOne("MESv2.Api.Models.Characteristic", "Characteristic")
                        .WithMany("DefectLocations")
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Characteristic");
                });

            modelBuilder.Entity("MESv2.Api.Models.DefectLog", b =>
                {
                    b.HasOne("MESv2.Api.Models.Characteristic", "Characteristic")
                        .WithMany("DefectLogs")
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.DefectCode", "DefectCode")
                        .WithMany("DefectLogs")
                        .HasForeignKey("DefectCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.HydroRecord", "HydroRecord")
                        .WithMany("DefectLogs")
                        .HasForeignKey("HydroRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.InspectionRecord", "InspectionRecord")
                        .WithMany("DefectLogs")
                        .HasForeignKey("InspectionRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.DefectLocation", "Location")
                        .WithMany("DefectLogs")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.ProductionRecord", "ProductionRecord")
                        .WithMany("DefectLogs")
                        .HasForeignKey("ProductionRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.User", "RepairedByUser")
                        .WithMany()
                        .HasForeignKey("RepairedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Characteristic");

                    b.Navigation("DefectCode");

                    b.Navigation("HydroRecord");

                    b.Navigation("InspectionRecord");

                    b.Navigation("Location");

                    b.Navigation("ProductionRecord");

                    b.Navigation("RepairedByUser");
                });

            modelBuilder.Entity("MESv2.Api.Models.DefectWorkCenter", b =>
                {
                    b.HasOne("MESv2.Api.Models.DefectCode", "DefectCode")
                        .WithMany()
                        .HasForeignKey("DefectCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "EarliestDetectionWorkCenter")
                        .WithMany()
                        .HasForeignKey("EarliestDetectionWorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany("DefectWorkCenters")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefectCode");

                    b.Navigation("EarliestDetectionWorkCenter");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.HydroRecord", b =>
                {
                    b.HasOne("MESv2.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Operator");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.InspectionRecord", b =>
                {
                    b.HasOne("MESv2.Api.Models.ControlPlan", "ControlPlan")
                        .WithMany("InspectionRecords")
                        .HasForeignKey("ControlPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany("InspectionRecords")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ControlPlan");

                    b.Navigation("Operator");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.MaterialQueueItem", b =>
                {
                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany("MaterialQueueItems")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.NameplateRecord", b =>
                {
                    b.HasOne("MESv2.Api.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("Product");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.Plant", b =>
                {
                    b.HasOne("MESv2.Api.Models.PlantGear", "CurrentPlantGear")
                        .WithMany()
                        .HasForeignKey("CurrentPlantGearId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentPlantGear");
                });

            modelBuilder.Entity("MESv2.Api.Models.PlantGear", b =>
                {
                    b.HasOne("MESv2.Api.Models.Plant", "Plant")
                        .WithMany("PlantGears")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("MESv2.Api.Models.Product", b =>
                {
                    b.HasOne("MESv2.Api.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("MESv2.Api.Models.ProductionLine", b =>
                {
                    b.HasOne("MESv2.Api.Models.Plant", "Plant")
                        .WithMany("ProductionLines")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("MESv2.Api.Models.ProductionRecord", b =>
                {
                    b.HasOne("MESv2.Api.Models.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.PlantGear", "PlantGear")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("PlantGearId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.SerialNumber", "SerialNumber")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("SerialNumberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Operator");

                    b.Navigation("PlantGear");

                    b.Navigation("ProductionLine");

                    b.Navigation("SerialNumber");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.RoundSeamSetup", b =>
                {
                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.SerialNumber", b =>
                {
                    b.HasOne("MESv2.Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.Vendor", "HeadsVendor")
                        .WithMany()
                        .HasForeignKey("HeadsVendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.Vendor", "MillVendor")
                        .WithMany()
                        .HasForeignKey("MillVendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.Vendor", "ProcessorVendor")
                        .WithMany()
                        .HasForeignKey("ProcessorVendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.Product", "Product")
                        .WithMany("SerialNumbers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.SerialNumber", "ReplaceBySN")
                        .WithMany()
                        .HasForeignKey("ReplaceBySNId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("HeadsVendor");

                    b.Navigation("MillVendor");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("ProcessorVendor");

                    b.Navigation("Product");

                    b.Navigation("ReplaceBySN");
                });

            modelBuilder.Entity("MESv2.Api.Models.SpotXrayIncrement", b =>
                {
                    b.HasOne("MESv2.Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.ProductionRecord", "ProductionRecord")
                        .WithMany()
                        .HasForeignKey("ManufacturingLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.User", "ModifiedByUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("ProductionRecord");
                });

            modelBuilder.Entity("MESv2.Api.Models.User", b =>
                {
                    b.HasOne("MESv2.Api.Models.Plant", "DefaultSite")
                        .WithMany("Users")
                        .HasForeignKey("DefaultSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultSite");
                });

            modelBuilder.Entity("MESv2.Api.Models.WelderLog", b =>
                {
                    b.HasOne("MESv2.Api.Models.Characteristic", "Characteristic")
                        .WithMany("WelderLogs")
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.ProductionRecord", "ProductionRecord")
                        .WithMany("WelderLogs")
                        .HasForeignKey("ProductionRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Characteristic");

                    b.Navigation("ProductionRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MESv2.Api.Models.WorkCenter", b =>
                {
                    b.HasOne("MESv2.Api.Models.WorkCenter", "MaterialQueueForWC")
                        .WithMany()
                        .HasForeignKey("MaterialQueueForWCId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MESv2.Api.Models.WorkCenterType", "WorkCenterType")
                        .WithMany("WorkCenters")
                        .HasForeignKey("WorkCenterTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialQueueForWC");

                    b.Navigation("WorkCenterType");
                });

            modelBuilder.Entity("MESv2.Api.Models.WorkCenterProductionLine", b =>
                {
                    b.HasOne("MESv2.Api.Models.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany("WorkCenterProductionLines")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionLine");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.WorkCenterWelder", b =>
                {
                    b.HasOne("MESv2.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.XrayQueueItem", b =>
                {
                    b.HasOne("MESv2.Api.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MESv2.Api.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MESv2.Api.Models.AnnotationType", b =>
                {
                    b.Navigation("Annotations");
                });

            modelBuilder.Entity("MESv2.Api.Models.Characteristic", b =>
                {
                    b.Navigation("DefectLocations");

                    b.Navigation("DefectLogs");

                    b.Navigation("WelderLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.ControlPlan", b =>
                {
                    b.Navigation("InspectionRecords");
                });

            modelBuilder.Entity("MESv2.Api.Models.DefectCode", b =>
                {
                    b.Navigation("DefectLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.DefectLocation", b =>
                {
                    b.Navigation("DefectLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.HydroRecord", b =>
                {
                    b.Navigation("DefectLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.InspectionRecord", b =>
                {
                    b.Navigation("DefectLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.Plant", b =>
                {
                    b.Navigation("PlantGears");

                    b.Navigation("ProductionLines");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MESv2.Api.Models.PlantGear", b =>
                {
                    b.Navigation("ProductionRecords");
                });

            modelBuilder.Entity("MESv2.Api.Models.Product", b =>
                {
                    b.Navigation("SerialNumbers");
                });

            modelBuilder.Entity("MESv2.Api.Models.ProductType", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("MESv2.Api.Models.ProductionRecord", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("DefectLogs");

                    b.Navigation("WelderLogs");
                });

            modelBuilder.Entity("MESv2.Api.Models.SerialNumber", b =>
                {
                    b.Navigation("ProductionRecords");
                });

            modelBuilder.Entity("MESv2.Api.Models.WorkCenter", b =>
                {
                    b.Navigation("Assemblies");

                    b.Navigation("Assets");

                    b.Navigation("CharacteristicWorkCenters");

                    b.Navigation("ControlPlans");

                    b.Navigation("DefectWorkCenters");

                    b.Navigation("InspectionRecords");

                    b.Navigation("MaterialQueueItems");

                    b.Navigation("ProductionRecords");

                    b.Navigation("WorkCenterProductionLines");
                });

            modelBuilder.Entity("MESv2.Api.Models.WorkCenterType", b =>
                {
                    b.Navigation("WorkCenters");
                });
#pragma warning restore 612, 618
        }
    }
}
