using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Moq;
using MESv2.Api.Controllers;
using MESv2.Api.DTOs;
using MESv2.Api.Services;

namespace MESv2.Api.Tests;

public class DowntimeEventsControllerTests
{
    [Fact]
    public async Task Create_UsesXUserIdHeader_WhenClaimMissing()
    {
        var userId = Guid.NewGuid();
        var dto = new CreateDowntimeEventDto
        {
            WorkCenterProductionLineId = Guid.NewGuid(),
            OperatorUserId = Guid.NewGuid(),
            StartedAt = DateTime.UtcNow.AddMinutes(-5),
            EndedAt = DateTime.UtcNow,
            DowntimeReasonId = Guid.NewGuid(),
            IsAutoGenerated = false,
        };

        var expected = new DowntimeEventDto { Id = Guid.NewGuid() };
        var service = new Mock<IDowntimeService>();
        service
            .Setup(x => x.CreateDowntimeEventAsync(dto, userId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(expected);

        var controller = new DowntimeEventsController(service.Object)
        {
            ControllerContext = new ControllerContext
            {
                HttpContext = new DefaultHttpContext(),
            },
        };
        controller.ControllerContext.HttpContext.Request.Headers["X-User-Id"] = userId.ToString();

        var result = await controller.Create(dto, CancellationToken.None);

        var created = Assert.IsType<ObjectResult>(result.Result);
        Assert.Equal(201, created.StatusCode);
        Assert.Same(expected, created.Value);
    }

    [Fact]
    public async Task Create_Returns401_WhenNoUserContextAvailable()
    {
        var dto = new CreateDowntimeEventDto
        {
            WorkCenterProductionLineId = Guid.NewGuid(),
            OperatorUserId = Guid.NewGuid(),
            StartedAt = DateTime.UtcNow.AddMinutes(-5),
            EndedAt = DateTime.UtcNow,
            IsAutoGenerated = false,
        };

        var service = new Mock<IDowntimeService>();
        var controller = new DowntimeEventsController(service.Object)
        {
            ControllerContext = new ControllerContext
            {
                HttpContext = new DefaultHttpContext(),
            },
        };

        var result = await controller.Create(dto, CancellationToken.None);

        var unauthorized = Assert.IsType<ObjectResult>(result.Result);
        Assert.Equal(401, unauthorized.StatusCode);
        service.Verify(
            x => x.CreateDowntimeEventAsync(It.IsAny<CreateDowntimeEventDto>(), It.IsAny<Guid>(), It.IsAny<CancellationToken>()),
            Times.Never);
    }
}
