using Microsoft.Extensions.Logging;
using Moq;
using MESv2.Api.Models;
using MESv2.Api.Services;

namespace MESv2.Api.Tests;

public class OeeServiceTests
{
    private static readonly Guid PlantId = TestHelpers.PlantPlt1Id;
    private static readonly Guid WcRollsId = TestHelpers.wcRollsId;
    private static readonly Guid Line1Id = TestHelpers.ProductionLine1Plt1Id;
    private static readonly Guid Gear3Id = Guid.Parse("61111111-1111-1111-1111-111111111113");
    private static readonly Guid WcplRollsLine1Id = Guid.Parse("d0010001-0000-0000-0000-000000000001");

    [Fact]
    public async Task CalculateOee_ReturnsEmpty_WhenNoShiftSchedule()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;
        var sut = new OeeService(db, logger);

        var result = await sut.CalculateOeeAsync(WcRollsId, PlantId, "2026-02-22");

        Assert.Null(result.Availability);
        Assert.Null(result.Performance);
    }

    [Fact]
    public async Task CalculateOee_ReturnsZeroPlannedMinutes_WhenDayIsOff()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;

        db.ShiftSchedules.Add(new ShiftSchedule
        {
            Id = Guid.NewGuid(),
            PlantId = PlantId,
            EffectiveDate = new DateOnly(2026, 1, 1),
            MondayHours = 10, MondayBreakMinutes = 30,
            TuesdayHours = 10, TuesdayBreakMinutes = 30,
            WednesdayHours = 10, WednesdayBreakMinutes = 30,
            ThursdayHours = 10, ThursdayBreakMinutes = 30,
            SundayHours = 0, SundayBreakMinutes = 0,
            CreatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();

        var sut = new OeeService(db, logger);

        // 2026-02-22 is a Sunday
        var result = await sut.CalculateOeeAsync(WcRollsId, PlantId, "2026-02-22");

        Assert.Equal(0m, result.PlannedMinutes);
    }

    [Fact]
    public async Task CalculateOee_ReturnsFullAvailability_WhenNoDowntime()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;

        db.ShiftSchedules.Add(new ShiftSchedule
        {
            Id = Guid.NewGuid(),
            PlantId = PlantId,
            EffectiveDate = new DateOnly(2026, 1, 1),
            MondayHours = 10, MondayBreakMinutes = 30,
            TuesdayHours = 10, TuesdayBreakMinutes = 30,
            WednesdayHours = 10, WednesdayBreakMinutes = 30,
            ThursdayHours = 10, ThursdayBreakMinutes = 30,
            FridayHours = 8, FridayBreakMinutes = 30,
            CreatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();

        var sut = new OeeService(db, logger);

        // 2026-02-23 is a Monday
        var result = await sut.CalculateOeeAsync(WcRollsId, PlantId, "2026-02-23");

        Assert.Equal(100.0m, result.Availability);
        Assert.Equal(570.0m, result.PlannedMinutes);
        Assert.Equal(0m, result.DowntimeMinutes);
        Assert.Equal(570.0m, result.RunTimeMinutes);
    }

    [Fact]
    public async Task CalculateOee_ReducesAvailability_WithDowntimeEvents()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;

        db.ShiftSchedules.Add(new ShiftSchedule
        {
            Id = Guid.NewGuid(),
            PlantId = PlantId,
            EffectiveDate = new DateOnly(2026, 1, 1),
            MondayHours = 10, MondayBreakMinutes = 0,
            CreatedAt = DateTime.UtcNow,
        });

        var operatorId = TestHelpers.TestUserId;
        db.DowntimeEvents.Add(new DowntimeEvent
        {
            Id = Guid.NewGuid(),
            WorkCenterProductionLineId = WcplRollsLine1Id,
            OperatorUserId = operatorId,
            StartedAt = new DateTime(2026, 2, 23, 12, 0, 0, DateTimeKind.Utc),
            EndedAt = new DateTime(2026, 2, 23, 13, 0, 0, DateTimeKind.Utc),
            DurationMinutes = 60,
            IsAutoGenerated = true,
            CreatedAt = DateTime.UtcNow,
        });
        await db.SaveChangesAsync();

        var sut = new OeeService(db, logger);
        var result = await sut.CalculateOeeAsync(WcRollsId, PlantId, "2026-02-23");

        Assert.Equal(600m, result.PlannedMinutes);
        Assert.Equal(60m, result.DowntimeMinutes);
        Assert.Equal(540m, result.RunTimeMinutes);
        Assert.Equal(90.0m, result.Availability);
    }

    [Fact]
    public async Task CalculateOee_ComputesPerformance_WithCapacityTargets()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;

        // Set plant's current gear
        var plant = await db.Plants.FindAsync(PlantId);
        plant!.CurrentPlantGearId = Gear3Id;

        db.ShiftSchedules.Add(new ShiftSchedule
        {
            Id = Guid.NewGuid(),
            PlantId = PlantId,
            EffectiveDate = new DateOnly(2026, 1, 1),
            MondayHours = 10, MondayBreakMinutes = 0,
            CreatedAt = DateTime.UtcNow,
        });

        // Target: 6 units per hour at gear 3 (null = default for all sizes)
        db.WorkCenterCapacityTargets.Add(new WorkCenterCapacityTarget
        {
            Id = Guid.NewGuid(),
            WorkCenterProductionLineId = WcplRollsLine1Id,
            TankSize = null,
            PlantGearId = Gear3Id,
            TargetUnitsPerHour = 6m,
        });

        // Add 60 production records on Monday (all at gear 3)
        var serial = new SerialNumber { Id = Guid.NewGuid(), Serial = "SN-OEE-1", CreatedAt = DateTime.UtcNow };
        db.SerialNumbers.Add(serial);

        for (int i = 0; i < 60; i++)
        {
            db.ProductionRecords.Add(new ProductionRecord
            {
                Id = Guid.NewGuid(),
                SerialNumberId = serial.Id,
                WorkCenterId = WcRollsId,
                ProductionLineId = Line1Id,
                OperatorId = TestHelpers.TestUserId,
                Timestamp = new DateTime(2026, 2, 23, 6, 0, 0, DateTimeKind.Utc).AddMinutes(i * 10),
                PlantGearId = Gear3Id,
            });
        }
        await db.SaveChangesAsync();

        var sut = new OeeService(db, logger);
        var result = await sut.CalculateOeeAsync(WcRollsId, PlantId, "2026-02-23");

        // 60 records * (60/6 = 10 min ideal cycle time each) = 600 ideal minutes
        // Run time = 600 min (10h, no downtime)
        // Performance = 600/600 = 100%
        Assert.Equal(100.0m, result.Availability);
        Assert.NotNull(result.Performance);
        Assert.Equal(100.0m, result.Performance);
    }

    [Fact]
    public async Task CalculateOee_PerformanceBelow100_WhenBelowTarget()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;

        var plant = await db.Plants.FindAsync(PlantId);
        plant!.CurrentPlantGearId = Gear3Id;

        db.ShiftSchedules.Add(new ShiftSchedule
        {
            Id = Guid.NewGuid(),
            PlantId = PlantId,
            EffectiveDate = new DateOnly(2026, 1, 1),
            MondayHours = 10, MondayBreakMinutes = 0,
            CreatedAt = DateTime.UtcNow,
        });

        db.WorkCenterCapacityTargets.Add(new WorkCenterCapacityTarget
        {
            Id = Guid.NewGuid(),
            WorkCenterProductionLineId = WcplRollsLine1Id,
            TankSize = null,
            PlantGearId = Gear3Id,
            TargetUnitsPerHour = 6m,
        });

        var serial = new SerialNumber { Id = Guid.NewGuid(), Serial = "SN-OEE-2", CreatedAt = DateTime.UtcNow };
        db.SerialNumbers.Add(serial);

        // Only 30 records instead of 60 needed for 100%
        for (int i = 0; i < 30; i++)
        {
            db.ProductionRecords.Add(new ProductionRecord
            {
                Id = Guid.NewGuid(),
                SerialNumberId = serial.Id,
                WorkCenterId = WcRollsId,
                ProductionLineId = Line1Id,
                OperatorId = TestHelpers.TestUserId,
                Timestamp = new DateTime(2026, 2, 23, 6, 0, 0, DateTimeKind.Utc).AddMinutes(i * 10),
                PlantGearId = Gear3Id,
            });
        }
        await db.SaveChangesAsync();

        var sut = new OeeService(db, logger);
        var result = await sut.CalculateOeeAsync(WcRollsId, PlantId, "2026-02-23");

        // 30 * 10min ideal = 300 ideal minutes / 600 run minutes = 50%
        Assert.NotNull(result.Performance);
        Assert.Equal(50.0m, result.Performance);
    }

    [Fact]
    public async Task CalculateOee_UsesExactTankSizeMatch_OverDefault()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;

        var plant = await db.Plants.FindAsync(PlantId);
        plant!.CurrentPlantGearId = Gear3Id;

        db.ShiftSchedules.Add(new ShiftSchedule
        {
            Id = Guid.NewGuid(),
            PlantId = PlantId,
            EffectiveDate = new DateOnly(2026, 1, 1),
            MondayHours = 10, MondayBreakMinutes = 0,
            CreatedAt = DateTime.UtcNow,
        });

        // Default target: 6 UPH
        db.WorkCenterCapacityTargets.Add(new WorkCenterCapacityTarget
        {
            Id = Guid.NewGuid(),
            WorkCenterProductionLineId = WcplRollsLine1Id,
            TankSize = null,
            PlantGearId = Gear3Id,
            TargetUnitsPerHour = 6m,
        });

        // Specific target for 120 gallon: 12 UPH (faster)
        db.WorkCenterCapacityTargets.Add(new WorkCenterCapacityTarget
        {
            Id = Guid.NewGuid(),
            WorkCenterProductionLineId = WcplRollsLine1Id,
            TankSize = 120,
            PlantGearId = Gear3Id,
            TargetUnitsPerHour = 12m,
        });

        // Get the 120 shell product
        var shellProduct = db.Products.First(p => p.TankSize == 120 && p.ProductType!.SystemTypeName == "shell");
        var serial = new SerialNumber
        {
            Id = Guid.NewGuid(), Serial = "SN-OEE-SIZE", ProductId = shellProduct.Id, CreatedAt = DateTime.UtcNow,
        };
        db.SerialNumbers.Add(serial);

        // 60 records of 120-gallon tanks
        for (int i = 0; i < 60; i++)
        {
            db.ProductionRecords.Add(new ProductionRecord
            {
                Id = Guid.NewGuid(),
                SerialNumberId = serial.Id,
                WorkCenterId = WcRollsId,
                ProductionLineId = Line1Id,
                OperatorId = TestHelpers.TestUserId,
                Timestamp = new DateTime(2026, 2, 23, 6, 0, 0, DateTimeKind.Utc).AddMinutes(i * 10),
                PlantGearId = Gear3Id,
            });
        }
        await db.SaveChangesAsync();

        var sut = new OeeService(db, logger);
        var result = await sut.CalculateOeeAsync(WcRollsId, PlantId, "2026-02-23");

        // 60 * (60/12 = 5 min) = 300 ideal min / 600 run min = 50%
        Assert.NotNull(result.Performance);
        Assert.Equal(50.0m, result.Performance);
    }

    // ---- Shift Schedule CRUD Tests ----

    [Fact]
    public async Task CreateAndGetShiftSchedules_RoundTrips()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;
        var sut = new OeeService(db, logger);

        var created = await sut.CreateShiftScheduleAsync(new DTOs.CreateShiftScheduleDto
        {
            PlantId = PlantId,
            EffectiveDate = "2026-03-01",
            MondayHours = 10, MondayBreakMinutes = 30,
            TuesdayHours = 10, TuesdayBreakMinutes = 30,
            WednesdayHours = 10, WednesdayBreakMinutes = 30,
            ThursdayHours = 10, ThursdayBreakMinutes = 30,
            FridayHours = 8, FridayBreakMinutes = 30,
        }, null);

        Assert.NotEqual(Guid.Empty, created.Id);
        Assert.Equal("2026-03-01", created.EffectiveDate);
        Assert.Equal(10m, created.MondayHours);

        var all = await sut.GetShiftSchedulesAsync(PlantId);
        Assert.Contains(all, s => s.Id == created.Id);
    }

    [Fact]
    public async Task DeleteShiftSchedule_Removes()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;
        var sut = new OeeService(db, logger);

        var created = await sut.CreateShiftScheduleAsync(new DTOs.CreateShiftScheduleDto
        {
            PlantId = PlantId,
            EffectiveDate = "2026-04-01",
            MondayHours = 8,
        }, null);

        var deleted = await sut.DeleteShiftScheduleAsync(created.Id);
        Assert.True(deleted);

        var all = await sut.GetShiftSchedulesAsync(PlantId);
        Assert.DoesNotContain(all, s => s.Id == created.Id);
    }

    // ---- Capacity Target CRUD Tests ----

    [Fact]
    public async Task CreateAndGetCapacityTargets_RoundTrips()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;
        var sut = new OeeService(db, logger);

        var created = await sut.CreateCapacityTargetAsync(new DTOs.CreateWorkCenterCapacityTargetDto
        {
            WorkCenterProductionLineId = WcplRollsLine1Id,
            TankSize = null,
            PlantGearId = Gear3Id,
            TargetUnitsPerHour = 10m,
        });

        Assert.NotEqual(Guid.Empty, created.Id);
        Assert.Equal(10m, created.TargetUnitsPerHour);

        var all = await sut.GetCapacityTargetsAsync(PlantId);
        Assert.Contains(all, t => t.Id == created.Id);
    }

    [Fact]
    public async Task DeleteCapacityTarget_Removes()
    {
        await using var db = TestHelpers.CreateInMemoryContext();
        var logger = new Mock<ILogger<OeeService>>().Object;
        var sut = new OeeService(db, logger);

        var created = await sut.CreateCapacityTargetAsync(new DTOs.CreateWorkCenterCapacityTargetDto
        {
            WorkCenterProductionLineId = WcplRollsLine1Id,
            TankSize = 120,
            PlantGearId = Gear3Id,
            TargetUnitsPerHour = 8m,
        });

        var deleted = await sut.DeleteCapacityTargetAsync(created.Id);
        Assert.True(deleted);

        var all = await sut.GetCapacityTargetsAsync(PlantId);
        Assert.DoesNotContain(all, t => t.Id == created.Id);
    }
}
