import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { FluentProvider, webLightTheme } from '@fluentui/react-components';
import { DowntimeOverlay } from './DowntimeOverlay';
import type { DowntimeReason } from '../../types/domain';

vi.mock('../../api/endpoints', () => ({
  downtimeEventApi: {
    create: vi.fn().mockResolvedValue({ id: 'evt-1' }),
  },
}));

const mockReasons: DowntimeReason[] = [
  { id: 'r1', downtimeReasonCategoryId: 'cat1', categoryName: 'Equipment', name: 'Breakdown', isActive: true, sortOrder: 0 },
  { id: 'r2', downtimeReasonCategoryId: 'cat1', categoryName: 'Equipment', name: 'Tooling', isActive: true, sortOrder: 1 },
  { id: 'r3', downtimeReasonCategoryId: 'cat2', categoryName: 'Personnel', name: 'Break', isActive: true, sortOrder: 0 },
];

function renderOverlay(overrides = {}) {
  const defaultProps = {
    lastActivityTimestamp: Date.now() - 300_000,
    reasons: mockReasons,
    workCenterProductionLineId: 'wcpl-1',
    operatorUserId: 'user-1',
    onDismiss: vi.fn(),
    ...overrides,
  };
  return {
    props: defaultProps,
    ...render(
      <FluentProvider theme={webLightTheme}>
        <DowntimeOverlay {...defaultProps} />
      </FluentProvider>
    ),
  };
}

describe('DowntimeOverlay', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders the overlay with title and reasons', () => {
    renderOverlay();
    expect(screen.getByText('Looks like there was some downtime')).toBeInTheDocument();
    expect(screen.getByText('Select a reason to continue')).toBeInTheDocument();
    expect(screen.getByText('Breakdown')).toBeInTheDocument();
    expect(screen.getByText('Tooling')).toBeInTheDocument();
    expect(screen.getByText('Break')).toBeInTheDocument();
  });

  it('groups reasons by category', () => {
    renderOverlay();
    expect(screen.getByText('Equipment')).toBeInTheDocument();
    expect(screen.getByText('Personnel')).toBeInTheDocument();
  });

  it('shows elapsed time timer', () => {
    renderOverlay();
    expect(screen.getByTestId('downtime-timer')).toBeInTheDocument();
  });

  it('calls API and dismisses on reason click', async () => {
    const { downtimeEventApi } = await import('../../api/endpoints');
    const { props } = renderOverlay();

    fireEvent.click(screen.getByText('Breakdown'));

    await waitFor(() => {
      expect(downtimeEventApi.create).toHaveBeenCalledWith(
        expect.objectContaining({
          workCenterProductionLineId: 'wcpl-1',
          operatorUserId: 'user-1',
          downtimeReasonId: 'r1',
          isAutoGenerated: false,
        })
      );
    });

    await waitFor(() => {
      expect(props.onDismiss).toHaveBeenCalled();
    });
  });
});
