import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { FluentProvider, webLightTheme } from '@fluentui/react-components';
import { MemoryRouter } from 'react-router-dom';
import { DowntimeEventsScreen } from './DowntimeEventsScreen';
import type { DowntimeEvent } from '../../types/domain';

vi.mock('../../api/endpoints', () => ({
  workCenterApi: {
    getWorkCenters: vi.fn().mockResolvedValue([
      { id: 'wc-1', name: 'Rolls', workCenterTypeId: 'wct-1', workCenterTypeName: 'Production', numberOfWelders: 0 },
    ]),
  },
  downtimeEventApi: {
    getAll: vi.fn().mockResolvedValue([]),
    create: vi.fn().mockResolvedValue({}),
    update: vi.fn().mockResolvedValue({}),
    delete: vi.fn().mockResolvedValue(undefined),
  },
  adminWorkCenterApi: { getProductionLineConfigs: vi.fn().mockResolvedValue([]) },
  downtimeReasonCategoryApi: { getAll: vi.fn().mockResolvedValue([]) },
  adminUserApi: { getAll: vi.fn().mockResolvedValue([]) },
}));

vi.mock('../../auth/AuthContext', () => ({
  useAuth: () => ({
    user: {
      id: 'user-1', displayName: 'Team Lead', roleTier: 5,
      plantCode: 'PLT1', plantName: 'Plant 1', defaultSiteId: 'site-1',
    },
    isAuthenticated: true,
    logout: vi.fn(),
  }),
}));

const { downtimeEventApi } = await import('../../api/endpoints');

const mockEvents: DowntimeEvent[] = [
  {
    id: 'evt-1',
    workCenterProductionLineId: 'wcpl-1',
    workCenterName: 'Rolls',
    productionLineName: 'Line 1',
    operatorUserId: 'op-1',
    operatorName: 'John Doe',
    downtimeReasonId: 'reason-1',
    downtimeReasonName: 'Breakdown',
    downtimeReasonCategoryName: 'Equipment',
    countsAsDowntime: true,
    startedAt: '2026-02-23T10:00:00Z',
    endedAt: '2026-02-23T10:15:00Z',
    durationMinutes: 15,
    isAutoGenerated: false,
    createdAt: '2026-02-23T10:15:00Z',
  },
  {
    id: 'evt-2',
    workCenterProductionLineId: 'wcpl-1',
    workCenterName: 'Rolls',
    productionLineName: 'Line 1',
    operatorUserId: 'op-2',
    operatorName: 'Jane Smith',
    startedAt: '2026-02-23T08:00:00Z',
    endedAt: '2026-02-23T09:00:00Z',
    durationMinutes: 60,
    countsAsDowntime: false,
    isAutoGenerated: true,
    createdAt: '2026-02-23T09:00:00Z',
  },
];

function renderScreen() {
  return render(
    <FluentProvider theme={webLightTheme}>
      <MemoryRouter>
        <DowntimeEventsScreen />
      </MemoryRouter>
    </FluentProvider>,
  );
}

async function selectWorkCenter(user: ReturnType<typeof userEvent.setup>) {
  await waitFor(() => {
    expect(screen.getByRole('combobox')).toBeInTheDocument();
  });
  await user.click(screen.getByRole('combobox'));
  await user.click(screen.getByText('Rolls'));
}

describe('DowntimeEventsScreen', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('shows prompt to select work center initially', async () => {
    renderScreen();
    await waitFor(() => {
      expect(screen.getByText(/select a work center to view/i)).toBeInTheDocument();
    });
  });

  it('loads and displays events when work center selected', async () => {
    vi.mocked(downtimeEventApi.getAll).mockResolvedValue(mockEvents);
    const user = userEvent.setup();

    renderScreen();
    await selectWorkCenter(user);

    await waitFor(() => {
      expect(screen.getByText('John Doe')).toBeInTheDocument();
      expect(screen.getByText('Jane Smith')).toBeInTheDocument();
      expect(screen.getByText('Breakdown')).toBeInTheDocument();
      expect(screen.getByText('Equipment')).toBeInTheDocument();
      expect(screen.getByText('Counts Toward OEE')).toBeInTheDocument();
      expect(screen.getByText('Yes')).toBeInTheDocument();
      expect(screen.getByText('No')).toBeInTheDocument();
    });
  });

  it('shows Auto and Manual badges', async () => {
    vi.mocked(downtimeEventApi.getAll).mockResolvedValue(mockEvents);
    const user = userEvent.setup();

    renderScreen();
    await selectWorkCenter(user);

    await waitFor(() => {
      expect(screen.getByText('Manual')).toBeInTheDocument();
      expect(screen.getByText('Auto')).toBeInTheDocument();
    });
  });

  it('shows empty state when no events found', async () => {
    vi.mocked(downtimeEventApi.getAll).mockResolvedValue([]);
    const user = userEvent.setup();

    renderScreen();
    await selectWorkCenter(user);

    await waitFor(() => {
      expect(screen.getByText(/no downtime events found/i)).toBeInTheDocument();
    });
  });

  it('displays duration with decimal format', async () => {
    vi.mocked(downtimeEventApi.getAll).mockResolvedValue(mockEvents);
    const user = userEvent.setup();

    renderScreen();
    await selectWorkCenter(user);

    await waitFor(() => {
      expect(screen.getByText('15.0 min')).toBeInTheDocument();
      expect(screen.getByText('60.0 min')).toBeInTheDocument();
    });
  });

  it('calls delete API when delete confirmed', async () => {
    vi.mocked(downtimeEventApi.getAll).mockResolvedValue(mockEvents);
    vi.mocked(downtimeEventApi.delete).mockResolvedValue(undefined);
    const user = userEvent.setup();

    renderScreen();
    await selectWorkCenter(user);

    await waitFor(() => {
      expect(screen.getByText('John Doe')).toBeInTheDocument();
    });

    const deleteButtons = screen.getAllByLabelText('Delete');
    await user.click(deleteButtons[0]);

    await waitFor(() => {
      expect(screen.getByText(/confirm deactivation/i)).toBeInTheDocument();
    });

    const confirmDialog = await screen.findByRole('dialog', { name: /confirm deactivation/i });
    await user.click(within(confirmDialog).getByRole('button', { name: /deactivate/i }));

    await waitFor(() => {
      expect(downtimeEventApi.delete).toHaveBeenCalledWith('evt-1');
    });
  });
});
