namespace MESv2.Api.DTOs;

// ---- Downtime Reason Categories ----
public class DowntimeReasonCategoryDto
{
    public Guid Id { get; set; }
    public Guid PlantId { get; set; }
    public string Name { get; set; } = string.Empty;
    public bool IsActive { get; set; }
    public int SortOrder { get; set; }
    public List<DowntimeReasonDto> Reasons { get; set; } = new();
}

public class CreateDowntimeReasonCategoryDto
{
    public Guid PlantId { get; set; }
    public string Name { get; set; } = string.Empty;
    public int SortOrder { get; set; }
}

public class UpdateDowntimeReasonCategoryDto
{
    public string Name { get; set; } = string.Empty;
    public int SortOrder { get; set; }
    public bool IsActive { get; set; } = true;
}

// ---- Downtime Reasons ----
public class DowntimeReasonDto
{
    public Guid Id { get; set; }
    public Guid DowntimeReasonCategoryId { get; set; }
    public string CategoryName { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public bool IsActive { get; set; }
    public bool CountsAsDowntime { get; set; } = true;
    public int SortOrder { get; set; }
}

public class CreateDowntimeReasonDto
{
    public Guid DowntimeReasonCategoryId { get; set; }
    public string Name { get; set; } = string.Empty;
    public bool CountsAsDowntime { get; set; } = true;
    public int SortOrder { get; set; }
}

public class UpdateDowntimeReasonDto
{
    public string Name { get; set; } = string.Empty;
    public int SortOrder { get; set; }
    public bool IsActive { get; set; } = true;
    public bool CountsAsDowntime { get; set; } = true;
}

// ---- Downtime Config (per WC/PL) ----
public class DowntimeConfigDto
{
    public bool DowntimeTrackingEnabled { get; set; }
    public int DowntimeThresholdMinutes { get; set; }
    public List<DowntimeReasonDto> ApplicableReasons { get; set; } = new();
}

public class UpdateDowntimeConfigDto
{
    public bool DowntimeTrackingEnabled { get; set; }
    public int DowntimeThresholdMinutes { get; set; }
}

public class SetDowntimeReasonsDto
{
    public List<Guid> ReasonIds { get; set; } = new();
}

// ---- Downtime Events ----
public class DowntimeEventDto
{
    public Guid Id { get; set; }
    public Guid WorkCenterProductionLineId { get; set; }
    public Guid OperatorUserId { get; set; }
    public string OperatorName { get; set; } = string.Empty;
    public Guid? DowntimeReasonId { get; set; }
    public string? DowntimeReasonName { get; set; }
    public string? DowntimeReasonCategoryName { get; set; }
    public DateTime StartedAt { get; set; }
    public DateTime EndedAt { get; set; }
    public decimal DurationMinutes { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
}

public class CreateDowntimeEventDto
{
    public Guid WorkCenterProductionLineId { get; set; }
    public Guid OperatorUserId { get; set; }
    public DateTime StartedAt { get; set; }
    public DateTime EndedAt { get; set; }
    public Guid? DowntimeReasonId { get; set; }
    public bool IsAutoGenerated { get; set; }
}
