namespace MESv2.Api.Models;

public class DowntimeEvent
{
    public Guid Id { get; set; }
    public Guid WorkCenterProductionLineId { get; set; }
    public Guid OperatorUserId { get; set; }
    public Guid? DowntimeReasonId { get; set; }
    public DateTime StartedAt { get; set; }
    public DateTime EndedAt { get; set; }
    public decimal DurationMinutes { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }

    public WorkCenterProductionLine WorkCenterProductionLine { get; set; } = null!;
    public User OperatorUser { get; set; } = null!;
    public DowntimeReason? DowntimeReason { get; set; }
    public ICollection<Annotation> Annotations { get; set; } = new List<Annotation>();
}
