import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import { FluentProvider, webLightTheme } from '@fluentui/react-components';
import { MemoryRouter } from 'react-router-dom';
import { LogDowntimeDialog } from './LogDowntimeDialog';
import { adminUserApi, adminWorkCenterApi } from '../../api/endpoints';

vi.mock('../../api/endpoints', () => ({
  workCenterApi: {
    getWorkCenters: vi.fn().mockResolvedValue([
      { id: 'wc-1', name: 'Rolls', workCenterTypeId: 'wct-1', workCenterTypeName: 'Production', numberOfWelders: 0 },
    ]),
  },
  adminWorkCenterApi: {
    getProductionLineConfigs: vi.fn().mockResolvedValue([
      { id: 'wcpl-1', workCenterId: 'wc-1', productionLineId: 'pl-1', productionLineName: 'Line 1', plantName: 'Plant 1', displayName: 'PLT1 Line 1', numberOfWelders: 2, downtimeTrackingEnabled: true, downtimeThresholdMinutes: 5 },
    ]),
  },
  downtimeReasonCategoryApi: {
    getAll: vi.fn().mockResolvedValue([
      { id: 'cat-1', plantId: 'site-1', name: 'Equipment', isActive: true, sortOrder: 0, reasons: [
        { id: 'reason-1', downtimeReasonCategoryId: 'cat-1', categoryName: 'Equipment', name: 'Breakdown', isActive: true, countsAsDowntime: true, sortOrder: 0 },
      ]},
    ]),
  },
  adminUserApi: {
    getAll: vi.fn().mockResolvedValue([
      { id: 'op-1', employeeNumber: 'EMP001', firstName: 'John', lastName: 'Doe', displayName: 'John Doe', roleTier: 6, roleName: 'Operator', defaultSiteId: 'site-1', defaultSiteName: 'Plant 1', isCertifiedWelder: false, requirePinForLogin: false, hasPin: false, userType: 0, isActive: true },
    ]),
  },
  downtimeEventApi: {
    create: vi.fn().mockResolvedValue({}),
    update: vi.fn().mockResolvedValue({}),
  },
}));

vi.mock('../../auth/AuthContext', () => ({
  useAuth: () => ({
    user: {
      id: 'user-1', displayName: 'Team Lead', roleTier: 5,
      plantCode: 'PLT1', plantName: 'Plant 1', defaultSiteId: 'site-1',
    },
    isAuthenticated: true,
    logout: vi.fn(),
  }),
}));

function renderDialog(props: Partial<Parameters<typeof LogDowntimeDialog>[0]> = {}) {
  return render(
    <FluentProvider theme={webLightTheme}>
      <MemoryRouter>
        <LogDowntimeDialog
          open
          onClose={vi.fn()}
          onSaved={vi.fn()}
          {...props}
        />
      </MemoryRouter>
    </FluentProvider>,
  );
}

describe('LogDowntimeDialog', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders dialog with title "Log Downtime" for new event', async () => {
    renderDialog();
    await waitFor(() => {
      expect(screen.getByText('Log Downtime')).toBeInTheDocument();
    });
  });

  it('renders dialog with title "Edit Downtime Event" for edit mode', async () => {
    renderDialog({
      editEvent: {
        id: 'evt-1',
        workCenterProductionLineId: 'wcpl-1',
        workCenterName: 'Rolls',
        productionLineName: 'Line 1',
        operatorUserId: 'op-1',
        operatorName: 'John Doe',
        downtimeReasonId: 'reason-1',
        downtimeReasonName: 'Breakdown',
        downtimeReasonCategoryName: 'Equipment',
        startedAt: '2026-02-23T10:00:00Z',
        endedAt: '2026-02-23T10:15:00Z',
        durationMinutes: 15,
        isAutoGenerated: false,
        createdAt: '2026-02-23T10:15:00Z',
      },
    });
    await waitFor(() => {
      expect(screen.getByText('Edit Downtime Event')).toBeInTheDocument();
    });
  });

  it('shows all form fields', async () => {
    renderDialog();
    await waitFor(() => {
      expect(screen.getByText('Work Center')).toBeInTheDocument();
      expect(screen.getByText('Production Line')).toBeInTheDocument();
      expect(screen.getByText('Operator')).toBeInTheDocument();
      expect(screen.getByText('Start Date')).toBeInTheDocument();
      expect(screen.getByText('Start Time')).toBeInTheDocument();
      expect(screen.getByText('End Date')).toBeInTheDocument();
      expect(screen.getByText('End Time')).toBeInTheDocument();
      expect(screen.getByText('Downtime Reason')).toBeInTheDocument();
    });
  });

  it('shows confirm button with correct label', async () => {
    renderDialog();
    await waitFor(() => {
      expect(screen.getByRole('button', { name: /log downtime/i })).toBeInTheDocument();
    });
  });

  it('does not render when closed', () => {
    renderDialog({ open: false });
    expect(screen.queryByText('Log Downtime')).not.toBeInTheDocument();
  });

  it('pre-selects work center when preselectedWorkCenterId is provided', async () => {
    renderDialog({ preselectedWorkCenterId: 'wc-1' });
    await waitFor(() => {
      expect(screen.getByText('Rolls')).toBeInTheDocument();
    });
  });

  it('loads plant-scoped operators and production lines', async () => {
    renderDialog({ preselectedWorkCenterId: 'wc-1' });

    await waitFor(() => {
      expect(adminUserApi.getAll).toHaveBeenCalledWith('site-1', [4, 5, 6]);
    });

    await waitFor(() => {
      expect(adminWorkCenterApi.getProductionLineConfigs).toHaveBeenCalledWith('wc-1', 'site-1');
    });
  });

  it('uses production line name in edit mode selection', async () => {
    renderDialog({
      preselectedWorkCenterId: 'wc-1',
      editEvent: {
        id: 'evt-1',
        workCenterProductionLineId: 'wcpl-1',
        workCenterName: 'Rolls',
        productionLineName: 'Line 1',
        operatorUserId: 'op-1',
        operatorName: 'John Doe',
        downtimeReasonId: 'reason-1',
        downtimeReasonName: 'Breakdown',
        downtimeReasonCategoryName: 'Equipment',
        startedAt: '2026-02-23T10:00:00Z',
        endedAt: '2026-02-23T10:15:00Z',
        durationMinutes: 15,
        isAutoGenerated: false,
        createdAt: '2026-02-23T10:15:00Z',
      },
    });

    await waitFor(() => {
      expect(screen.getByText('Line 1')).toBeInTheDocument();
    });
  });
});
